[package]
name = "iceblock-jade"
version = "0.1.0"
authors = ["Sam Sieber <swsieber@gmail.com>"]

[dependencies]
iceblock = { path = "../iceblock" }
igloo_macro = { path = "../igloo_macro" }
gen_test = { path = "../gen_test" }

[dev-dependencies]
compiletest_rs = "*"